CONTIKI_PROJECT = inga-demo
all: $(CONTIKI_PROJECT)
	
CFLAGS += -DDEBUG=1

TARGET=inga

CONTIKI = ../../..
# Choose NETSTACK here, IPV6 is default 
# CONTIKI_WITH_RIME = 1
include $(CONTIKI)/Makefile.include
