CONTIKI_PROJECT = inphase-shell 
PROJECT_SOURCEFILES += shell-inphasectl.c inphasectl.c
all: $(CONTIKI_PROJECT)

APPS = serial-shell
CONTIKI = ../..
CONTIKI_WITH_RIME = 1
CONTIKI_WITH_IPV6 = 1
include $(CONTIKI)/Makefile.include
