all: udp_ipv6_client udp_ipv6_server rime_unicast_receiver rime_unicast_sender

TARGET=inga

# Only for uip examples
#UIP_CONF_IPV6=1

CONTIKI = ../../..
CONTIKI_WITH_RIME = 1
CONTIKI_WITH_IPV6 = 1

include $(CONTIKI)/Makefile.include
