# RIME unicast test
rime-unicast-sender: rime_unicast_sender

rime-unicast-receiver: rime_unicast_receiver


# RIME broadcast test

TARGET = inga

APPS = settings_set

PROJECT_SOURCEFILES += ../test.c

CONTIKI = ../../..
CONTIKI_WITH_RIME = 1
CONTIKI_WITH_IPV6 = 1
include $(CONTIKI)/Makefile.include
